### ISSUE TITLE
Support for Logstash 5.1.1?

### ISSUE THREAD

**Issue by mrauter** [revpoint/logstash-codec-avro_schema_registry#1]
Are you supporting logstash 5.1.1?

Bundler::VersionConflict: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.1.1)

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.1.1) java

    logstash-codec-avro_schema_registry (>= 0) java depends on
      logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-core (>= 0) java

**Comment by ryananguiano** [comment]
@mrauter this should now be fixed in version 0.9.1. Try installing the latest version from RubyGems
