### ISSUE TITLE
Requires avsc or existing registered schema? 

### ISSUE THREAD

**Issue by rmoff** [revpoint/logstash-codec-avro_schema_registry#11]
Does this require a schema to already exist in the Schema Registry, or for the user to provide an `avsc`? 

I'm getting `io.confluent.rest.exceptions.RestNotFoundException: Schema not found` using this config: 

```
      codec => avro_schema_registry {
      endpoint => "http://localhost:8081"
      schema_id => 1
        register_schema => true
      binary_encoded => true
    }
    value_serializer => "org.apache.kafka.common.serialization.ByteArraySerializer"
```

**Comment by ryananguiano** [comment]
`schema_id` should only be used if the schema already exists. Otherwise, you should use `schema_string` or `schema_uri` to pass the .avsc file. 

Also look at the `check_compatibility` and `register_schema` options depending on your use case.

**Comment by klaricl** [comment]
Can you please tell what exact does the schema_string represent? Is there maybe a way to setup the (namespace+)name os the schema?
