### ISSUE TITLE
Add encode capability

### ISSUE THREAD

**Issue by ryananguiano** [revpoint/logstash-codec-avro_schema_registry#2]
Requested by @malonej7 and others.

We need to develop the encode capabilities using Confluent Avro Schema Registry. Luckily schema registration is already taken care of by https://github.com/wvanbergen/schema_registry so we just need to figure out the settings interface.

The options that need to be added:
- subject_name
- schema_uri
- schema_string
- check_compatibility
- override_compatibility

If anyone can think of anything else they would need, feel free to add them here. I might have time to take a crack at this soon unless someone else wants to give it a try. I will be happy to help walk anyone through it.

**Comment by ryananguiano** [comment]
https://github.com/logstash-plugins/logstash-codec-avro/issues/14#issuecomment-217989763

**Comment by cgiraldo** [comment]
I have implemented a basic encoder -> #4

**Comment by ryananguiano** [comment]
I updated the encode method, but still needs to be tested -> #5

**Comment by ryananguiano** [comment]
Merged onto master
